language: python
python:
- '3.8'
- '3.7'
- '3.6'
- '3.5'
- 3.8-dev
- 3.7-dev
- 3.6-dev
- 3.5-dev
env:
- GEVENT=true
- GEVENT=false
install:
- pip install PyYaml gevent pytest-random-order
before_script:
- export TZ=Asia/Jerusalem
script:
- python -m pytest --random-order-bucket=package -vv test_package.py
- python -m pytest --random-order-bucket=package -vv tests
- python -m pytest --random-order-bucket=package -vv --doctest-modules easypy
notifications:
  email:
    on_success: change
    on_failure: change
jobs:
  include:
    - stage: deploy
      python: 3.8
      deploy:
        provider: pypi
        user: __token__
        if: branch = master
        on:
          tags: true
          branch: master
        skip_existing: true
