stages:
  - name: test
    if: tag IS blank
  - name: deploy
    if: tag IS present
language: python
python:
- '3.8'
- '3.7'
- '3.6'
- '3.5'
- 3.8-dev
- 3.7-dev
- 3.6-dev
- 3.5-dev
env:
- EASYPY_AUTO_PATCH_GEVENT=true
- EASYPY_AUTO_PATCH_GEVENT=false
- EASYPY_AUTO_PATCH_LOGGING=logging
- EASYPY_AUTO_PATCH_LOGGING=logbook
install:
- pip install PyYaml gevent pytest-random-order logbook
before_script:
- export TZ=Asia/Jerusalem
script:
- python -m pytest --random-order-bucket=package -vv test_package.py
- python -m pytest --random-order-bucket=package -vv tests
- python -m pytest --random-order-bucket=package -vv --doctest-modules easypy
notifications:
  email:
    on_success: change
    on_failure: change
jobs:
  include:
    - stage: deploy
      python: '3.8'
      env: GEVENT=false
      script: skip
      install: skip
      deploy:
        provider: pypi
        user: __token__
        on:
          tags: true
          branch: master
        skip_existing: true
